language: node_js
node_js:
  - "10"

cache: yarn

install:
  - yarn

stages:
  - name: deploy
    if: tag IS present
  - name: trigger-go-dvpn-web
    if: tag IS present

jobs:
  include:
    - stage: deploy
      name: "Deploy"
      script: skip
      before_deploy:
        - mkdir releases
        - yarn run build
        - tar -zcvf dist.tar.gz build/
        - echo uname -a
      deploy:
        - provider: releases
          file_glob: true
          file: dist.tar.gz
          overwrite: true
          skip_cleanup: true
          api_key: "$GITHUB_API_KEY"
          on:
            tags: true

    - stage: trigger-go-dvpn-web
      name: "Trigger go-dvpn-web build"
      script:
        - ./bin/trigger-go-build.sh ${TRAVIS_API_TOKEN} ${TRAVIS_TAG}
