language: node_js
node_js:
  - "10"

cache: yarn

install:
  - yarn

before_install:
  - if [ -z "$TRAVIS_TAG" ]; then
    export TRAVIS_TAG=0.0.0-dev;
    fi

stages:
  - name: deploy-dev
    if: type != pull_request AND branch = master AND tag IS blank
  - name: deploy
    if: tag IS present

jobs:
  include:
    #    - stage: test
    #      name: "Test"
    #      script:
    #        - yarn test

    - stage: deploy-dev
      name: "Deploy 0.0.0-dev"
      script:
        - git tag -f $TRAVIS_TAG
        - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
        - git push gh :refs/tags/$TRAVIS_TAG
        - git push -f gh $TRAVIS_TAG

    - stage: deploy
      name: "Deploy"
      script: skip
      before_deploy:
        - mkdir releases
        - yarn run build
        - tar -zcvf dist.tar.gz build/
        - echo uname -a
      deploy:
        - provider: releases
          file_glob: true
          file: dist.tar.gz
          overwrite: true
          skip_cleanup: true
          api_key: "$GITHUB_API_KEY"
          on:
            tags: true
      after_success:
        - >
          curl -X POST \
          https://api.travis-ci.com/repo/mysteriumnetwork%2Fgo-dvpn-web/requests \
          -H 'authorization: token ${TRAVIS_API_TOKEN}' \
          -H 'cache-control: no-cache' \
          -H 'content-type: application/json' \
          -H 'travis-api-version: 3' \
          -d '{ "request": {
            "config": {
              "env": {
                "GIT_TAG_VERSION": "${TRAVIS_TAG}"
              }
            }}
          }'
